version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - eduagi-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./teaching.db
      - SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:3001,http://localhost:3000
    volumes:
      - ./data:/app/data
      - ./upload:/app/upload
    networks:
      - eduagi-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - eduagi-network

networks:
  eduagi-network:
    driver: bridge

volumes:
  data:
  upload: 
 
 