[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend; uvicorn app:app --host 0.0.0.0 --port 8000"

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
DATABASE_URL = "sqlite:///./teaching.db"
SECRET_KEY = "your-secret-key-here"
CORS_ORIGINS = "https://your-frontend-domain.com"

[build.packages]
python = "3.11"

[build.scripts]
backend-install = "cd backend; pip install -r requirements.txt"
frontend-install = "cd frontend; cp package-minimal.json package.json; npm ci"
frontend-build = "cd frontend; npm run build" 